### ISSUE TITLE
SocksClientError

### ISSUE THREAD

**Issue by ServerSideProject** [u9g/tutorials#1]
`SocksClientError: connect ETIMEDOUT 88.135.44.86:4153
    at SocksClient.closeSocket (C:\Users\Xcc_Owner\Desktop\Physics Bypass\node_modules\socks\bu
ild\client\socksclient.js:387:32)
    at SocksClient.onErrorHandler (C:\Users\Xcc_Owner\Desktop\Physics Bypass\node_modules\socks
\build\client\socksclient.js:360:14)
    at Socket.onError (C:\Users\Xcc_Owner\Desktop\Physics Bypass\node_modules\socks\build\clien
t\socksclient.js:222:38)
    at Object.onceWrapper (events.js:483:26)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  options: {
    proxy: {
      host: '88.135.44.86',
      port: 4153,
      type: 4,
      userId: '',
      password: ''
    },
    command: 'connect',
    destination: { host: 'ult11.falix.gg', port: 28444 }
  }
}`

**Comment by u9g** [comment]
It's a bad proxy

**Comment by ServerSideProject** [comment]
> It's a bad proxy

I tried different proxies, paid and free, still doesn't work
